import pytest
import os
import sys

# Isolate databases during testing to prevent locking issues
os.environ["TESTING"] = "true"

import sqlite3
import duckdb

from datetime import datetime, timedelta

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from database.db import get_db_connection, init_db
from database.warehouse import get_warehouse_connection, init_warehouse
from simulator.order_simulator import OrderSimulator
from orchestrator.etl import run_etl_pipeline

@pytest.fixture(autouse=True)
def setup_databases():
    # Initialize both databases fresh for testing
    init_db()
    init_warehouse()

def test_etl_pipeline_integration():
    # 1. Start the simulator and generate a few orders
    sim = OrderSimulator()
    # Speed up simulation: 1 sec real time = 240 min simulation time
    sim.set_config(weather="Rain", order_rate=4.0, speed_multiplier=240.0)
    sim.start()
    
    # Let simulator run for 4 seconds to schedule and emit events
    import time
    time.sleep(4)
    sim.stop()
    
    # 2. Check if we have events in OLTP database
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM order_events")
    event_count = cursor.fetchone()[0]
    conn.close()
    
    print(f"Generated {event_count} events in SQLite")
    assert event_count > 0, "No events were generated by simulator"
    
    # 3. Trigger ETL pipeline
    result = run_etl_pipeline()
    
    print(f"ETL completed: {result}")
    assert result["status"] == "success"
    
    # 4. Verify DuckDB analytical warehouse
    olap_conn = get_warehouse_connection()
    
    # Check fact table rows
    fact_count = olap_conn.execute("SELECT COUNT(*) FROM fact_orders").fetchone()[0]
    print(f"Fact orders loaded in DuckDB: {fact_count}")
    
    # Check date dimension rows
    date_count = olap_conn.execute("SELECT COUNT(*) FROM dim_dates").fetchone()[0]
    print(f"Date dimensions loaded: {date_count}")
    
    # Verify that we can query compliance metrics
    metrics = olap_conn.execute('''
        SELECT 
            COUNT(*) as total_orders,
            SUM(CASE WHEN is_breached = TRUE THEN 1 ELSE 0 END) as breached_orders,
            AVG(actual_duration_mins) as avg_duration
        FROM fact_orders
    ''').fetchone()
    
    print(f"Warehouse analytics: Total={metrics[0]}, Breached={metrics[1]}, AvgDuration={metrics[2]}")
    
    olap_conn.close()
    
    # Since some orders may not have completed yet, processed_count could be >= 0.
    # But if there are completed orders, fact_count should match the metrics.
    assert fact_count == result["processed_count"]
